services:
  - type: web
    name: quini6-api
    env: node
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    disk:
      name: quini6-disk
      mountPath: /opt/render/project/data
      sizeGB: 1